<a href="https://colab.research.google.com/github/jhonGarcia30/inteligencia-artificial/blob/main/Lunes01_Julio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as algebraLineal


a = algebraLineal.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[:2])
print(a[1:3])


a[1]=88
print(a)



(3,)
<class 'numpy.ndarray'>
[11 22 33]
[11 22]
[22 33]
[11 88 33]


In [1]:
from re import sub
#dos dimensiones

import numpy as np

b=np.array([[1,2,3],[11,22,33], [111,222,333]])
print(b.shape)
print(type(b))
print(b)

print(b[1,1])

submatriz = b[1:3, 1:3].copy()
print(submatriz.shape)
print("antes")
print(submatriz)

submatriz[1]=88
print("despues")
print(submatriz)
print(b)


(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
antes
[[ 22  33]
 [222 333]]
despues
[[22 33]
 [88 88]]
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


In [2]:
#matriz de dos dimensiones con el modulo zero
import numpy as np

c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [3]:
#matriz con la diagonal que tenga como elemento la unidad

e=np.eye(3,3)
print(e)

f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
g=np.random.random((5,5))
print(g)

#crear una matriz aleatoria que solo contenga elementos enteros, sea de 4x3 y que contenga solo numeros hasta el 20

matriz_aleatoria = np.random.randint(1, 21, size=(4, 3))
print(matriz_aleatoria)

[[0.65703933 0.83290497 0.91661319 0.05232035 0.48130004]
 [0.35528233 0.3208904  0.75077101 0.59549499 0.51612284]
 [0.6517243  0.65941174 0.97479886 0.14820859 0.99861544]
 [0.86142    0.03364421 0.24148377 0.4019896  0.68195475]
 [0.96991866 0.68145517 0.3073014  0.94593683 0.92094079]]
[[20  2 19]
 [16  6 20]
 [17 20  6]
 [ 7 14  9]]


In [5]:
tmp1=np.random.randint(1,20, (4,4))
print(tmp1)

rows=np.array([0,1,2,0])
cols=np.arange(4)

print(rows)
print(cols)

[[ 9 18 15 11]
 [11 16  5  8]
 [ 8  4  7 19]
 [ 1  3  3 10]]
[0 1 2 0]
[0 1 2 3]


In [6]:
tmp1[rows, cols]=100
print(tmp1)


[[100  18  15 100]
 [ 11 100   5   8]
 [  8   4 100  19]
 [  1   3   3  10]]


In [7]:
#Matriz aleatoria de 6x6 pero que los elementos sean del 20 al 50


tmp1=np.random.randint(20,50, (6,6))
print(tmp1)

[[23 32 47 30 35 44]
 [24 24 21 31 49 48]
 [48 34 26 37 24 47]
 [35 30 25 39 47 45]
 [38 46 40 36 39 23]
 [33 47 22 49 26 36]]


In [8]:
filter = (tmp1 > 45)
print(filter)
print(tmp1[filter])

[[False False  True False False False]
 [False False False False  True  True]
 [ True False False False False  True]
 [False False False False  True False]
 [False  True False False False False]
 [False  True False  True False False]]
[47 49 48 48 47 47 46 47 49]


In [9]:
#imprimir los números pares, los rangos pueden ser del 1 al 100

tmp1=np.random.randint(1,100, (10,10))
print(tmp1)

[[82 17 70 40 41  8 43 65 71 69]
 [22 75 46 40 62 16 90 33 47 40]
 [47  8 47 37 95 43 46 23 26 33]
 [36 21 77 90 21 77 19 16 64 24]
 [ 4 84  2 59 73 76 73 97 14  2]
 [79 59 29 29 96 82 53 76 21 93]
 [51  1 49 58 16 85 20 75 13 76]
 [12 82 10 99 29 46 51 79 80 22]
 [58 24 36 24 26 19 52 62 73 32]
 [32 46 71 98 96  4 81 29  8 78]]


In [10]:
filter = (tmp1%2==0)
print(filter)
print(tmp1[filter])

[[ True False  True  True False  True False False False False]
 [ True False  True  True  True  True  True False False  True]
 [False  True False False False False  True False  True False]
 [ True False False  True False False False  True  True  True]
 [ True  True  True False False  True False False  True  True]
 [False False False False  True  True False  True False False]
 [False False False  True  True False  True False False  True]
 [ True  True  True False False  True False False  True  True]
 [ True  True  True  True  True False  True  True False  True]
 [ True  True False  True  True  True False False  True  True]]
[82 70 40  8 22 46 40 62 16 90 40  8 46 26 36 90 16 64 24  4 84  2 76 14
  2 96 82 76 58 16 20 76 12 82 10 46 80 22 58 24 36 24 26 52 62 32 32 46
 98 96  4  8 78]


In [11]:

tmp3 = np.array([1,2,3,4,5],dtype=np.float64)
print(tmp3.dtype)

float64


In [12]:
x=np.array([[1,2],[11,22]])
y=np.array([[22,33],[44,55]])
print(x)
print(y)

print("La suma")
print(np.add(x,y))
print("La resta")
print(np.subtract(x,y))
print("multiplicación")
print(np.multiply(x,y))
print("División")
print(np.divide(x,y))
print("raiz cuadrada")
print(np.sqrt(x))

[[ 1  2]
 [11 22]]
[[22 33]
 [44 55]]
La suma
[[23 35]
 [55 77]]
La resta
[[-21 -31]
 [-33 -33]]
multiplicación
[[  22   66]
 [ 484 1210]]
División
[[0.04545455 0.06060606]
 [0.25       0.4       ]]
raiz cuadrada
[[1.         1.41421356]
 [3.31662479 4.69041576]]


In [13]:
tmp1=np.random.randint(1,10, (2,5))
print(tmp1)
#promedio
aux = tmp1.mean()
print(aux)

[[6 2 5 8 7]
 [8 8 2 1 2]]
4.9


In [14]:
print(tmp1.mean(axis=1))
print(tmp1.mean(axis=0))

[5.6 4.2]
[7.  5.  3.5 4.5 4.5]


In [15]:
import numpy as np
a=np.random.randint(1,10,(3,4))
print(a)
tmp=np.mean(a)
print(tmp)
print(a.mean())
tmp=a.mean(axis=1)
print(tmp)

aux=a.sum()
print(aux)
medianValue=np.median(a,axis=1)
print(medianValue)

[[6 9 8 7]
 [4 1 7 9]
 [3 6 4 1]]
5.416666666666667
5.416666666666667
[7.5  5.25 3.5 ]
65
[7.5 5.5 3.5]


In [16]:
#SORTING
b=np.random.randn(10)
print(b)
print(b.shape)
b.sort()
print(b)

[ 1.20578458  0.40424088 -0.20801386 -0.05568992  2.11027575  0.40854793
  0.50275825 -0.08767746  0.86142748  0.47125615]
(10,)
[-0.20801386 -0.08767746 -0.05568992  0.40424088  0.40854793  0.47125615
  0.50275825  0.86142748  1.20578458  2.11027575]


In [17]:
c=np.array([2,3,4,2,5,3,5])
print(np.unique(c))

[2 3 4 5]


In [18]:
string1=np.array(['desk','chair','bulb'])
string2=np.array(['lamp','bulb','chair'])

tmp1=np.intersect1d(string1,string2)
print(tmp1)
tmp2=np.union1d(string1,string2)
print(tmp2)
tmp3=np.setdiff1d(string1,string2)
print(tmp3)
tmp4=np.in1d(string1,string2)
print(tmp4)

['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


In [19]:
#BROADCASTING

aux=np.zeros((4,3))
print(aux)
replicate=np.array([1,2,1])
aux=aux+replicate
print(aux)

replicateCol=np.array([10,10,10])
print(replicateCol.shape)
replicateCol=np.reshape(replicateCol,(3,1))
print(replicateCol.shape)
aux=np.zeros((3,3))
aux1=replicateCol+aux
print(aux1)

print('we are here.........')
vector=np.array([45])
matrixZeros=np.zeros((5,5))
print(matrixZeros)
print(matrixZeros+vector)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]
 [1. 2. 1.]]
(3,)
(3, 1)
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]
we are here.........
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
