<a href="https://colab.research.google.com/github/jhonGarcia30/inteligencia-artificial/blob/main/trabajoIAtc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Verificar la versión de numpy
print(np.__version__)




1.25.2


In [ ]:
import numpy as np

# Crear un array unidimensional de números del 0 al 9
array_1d = np.arange(10)
print(array_1d)



[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

# Crear un vector aleatorio de tamaño 10
random_vector = np.random.rand(10)
print("Vector aleatorio original:", random_vector)

# Reemplazar el valor máximo en el vector por 0
random_vector[random_vector.argmax()] = 0
print("Vector después de reemplazar el valor máximo por 0:", random_vector)


Vector aleatorio original: [0.79993207 0.28196677 0.30593506 0.57516955 0.74458541 0.16408828
 0.80529664 0.68384442 0.77027291 0.27853368]
Vector después de reemplazar el valor máximo por 0: [0.79993207 0.28196677 0.30593506 0.57516955 0.74458541 0.16408828
 0.         0.68384442 0.77027291 0.27853368]


In [ ]:
import numpy as np

# Array dado
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Imprimir el número 8
number_8 = arr[1, 2]
print(number_8)


8


In [ ]:
import numpy as np

# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los números [3, 4, 5]
subset = arr[2:5]
print(subset)


[3 4 5]


In [ ]:
import numpy as np

# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los últimos 4 números
last_four_numbers = arr[-4:]
print(last_four_numbers)


[4 5 6 7]


In [ ]:
import numpy as np

# Crear un array de 3x3 con todos los valores True
array_true = np.full((3, 3), True)
print(array_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
import numpy as np

# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extraer todos los números impares
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


In [ ]:
import numpy as np

# Crear un vector con valores del 10 al 49
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
def reverse_vector(vector):
    return vector[::-1]

# Ejemplo:
original_vector = [1, 2, 3, 4, 5]
reversed_vector = reverse_vector(original_vector)
print("Original:", original_vector)
print("Invertido:", reversed_vector)

Original: [1, 2, 3, 4, 5]
Invertido: [5, 4, 3, 2, 1]


In [ ]:
import numpy as np

# Uuna matriz de 10x10 con valores enteros aleatorios entre 0 y 100
array = np.random.randint(0, 101, size=(10, 10))

# Encuentra valores mínimos y máximos.
min_value = np.min(array)
max_value = np.max(array)

print("Array:")
print(array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)



Array:
[[37 82 94 20  3 39 62 31  4 26]
 [98  4 94 33 40 99 48 28 53 27]
 [97 43 79 62 61 56 21 75  5  0]
 [95  0 34  3 10 13 88 33 26  6]
 [46 55 40 44 91 43 20  8 42 49]
 [74 46 30 37  7 80 25 46 11 46]
 [27 10 47  1  8 80 86 93 80 39]
 [ 0 76 54 68 73 22 93 13 72 78]
 [38 42 30 83  2  9 83 38 24  4]
 [44 72 17 34 66 75 37 31 10 87]]

Minimum value: 0
Maximum value: 99


In [ ]:
import numpy as np

# Una matriz de 3x3x3 con valores aleatorios
array = np.random.rand(3, 3, 3)

print("Matriz 3x3x3 con valores aleatorios:")
print(array)


Matriz 3x3x3 con valores aleatorios:
[[[0.40695467 0.61969247 0.22187333]
  [0.22942819 0.64076289 0.24951707]
  [0.41777918 0.71541718 0.27625459]]

 [[0.80174535 0.67366771 0.12508203]
  [0.70538798 0.45617565 0.40596315]
  [0.09298935 0.68017773 0.8039743 ]]

 [[0.7982543  0.4232854  0.04920325]
  [0.82045196 0.40054061 0.5250214 ]
  [0.78654227 0.37108078 0.81903706]]]


In [ ]:
import numpy as np

# Matriz de ejemplo
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reemplazar números impares con -1
arr[arr % 2 != 0] = -1

print("Matriz modificada:")
print(arr)



Matriz modificada:
[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [ ]:
import numpy as np

# Crea una matriz de tipo float
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]], dtype=float)

print("Matriz de tipo flotante:")
print(arr)


Matriz de tipo flotante:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
import numpy as np

# Ejemplo de matriz 1D
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Convertir a una matriz 2D con 2 filas
arr_2d = arr_1d.reshape(2, -1)  # -1 en remodelación infiere la dimensión restante

print("Original 1D matriz:")
print(arr_1d)
print("\nMatriz 2D convertida con 2 filas:")
print(arr_2d)


Original 1D matriz:
[1 2 3 4 5 6]

Matriz 2D convertida con 2 filas:
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

# Matrices de ejemplo
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Encuentre valores comunes entre Z1 y Z2
common_values = np.intersect1d(Z1, Z2)

print("Matriz Z1:", Z1)
print("Matriz Z2:", Z2)
print("\nValores comunes entre Z1 y Z2:", common_values)

Matriz Z1: [0 1 1 4 5 0 4 4 6 4]
Matriz Z2: [7 7 3 2 5 3 1 7 1 3]

Valores comunes entre Z1 y Z2: [1 5]


In [ ]:
import numpy as np

# Generar matrices aleatorias A y B
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Compruebe si las matrices A y B son iguales
are_equal = np.array_equal(A, B)

print("Matriz A:", A)
print("Matriz B:", B)

if are_equal:
    print("\nLas matrices A y B son iguales.")
else:
    print("\nLas matrices A y B no son iguales.")



Matriz A: [1 0 0 1 0]
Matriz B: [1 0 1 1 1]

Las matrices A y B no son iguales.


In [ ]:
import numpy as np

# Matrices de ejemplo
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

# Apilar matrices a y b verticalmente
stacked_array = np.vstack((a, b))

print("Matriz a:")
print(a)
print("\nMatriz b:")
print(b)
print("\nMatriz apilada verticalmente:")
print(stacked_array)



Matriz a:
[[1 2 3]
 [4 5 6]]

Matriz b:
[[ 7  8  9]
 [10 11 12]]

Matriz apilada verticalmente:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np

# Matrices de ejemplo
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Apilar las matrices a y b horizontalmente
stacked_array = np.hstack((a, b))

print("Matriz a:")
print(a)
print("\nMatriz b:")
print(b)
print("\nMatriz apilada horizontalmente:")
print(stacked_array)


Matriz a:
[[1 2]
 [3 4]]

Matriz b:
[[5 6]
 [7 8]]

Matriz apilada horizontalmente:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

tmp = np.arange(15)

# Consigue artículos entre 5 y 10
result = tmp[(tmp > 5) & (tmp < 10)]

print("Matriz original tmp:")
print(tmp)
print("\nArtículos entre 5 y 10:")
print(result)


Matriz original tmp:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Artículos entre 5 y 10:
[6 7 8 9]


In [ ]:
import numpy as np

def pair_max(x, y):
    """Obtenga el máximo de elementos de dos matrices"""
    return np.maximum(x, y)

# Ejemplo:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)


[6 7 9 8 9 7 5]


In [ ]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print("Original matriz:")
print(arr)

# Intercambiar columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nMatriz después de intercambiar las columnas 1 y 2:")
print(arr)


Original matriz:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Matriz después de intercambiar las columnas 1 y 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
import numpy as np

# Genere una matriz de 5x3 de números decimales aleatorios entre 5 y 10
arr = np.random.uniform(5, 10, size=(5, 3))

print("Matriz aleatoria de 5x3 entre 5 y 10:")
print(arr)

Matriz aleatoria de 5x3 entre 5 y 10:
[[8.56978801 9.03188632 5.26661053]
 [9.83478135 9.78667195 7.41111792]
 [9.26850657 5.18296201 7.77968614]
 [7.88894263 5.849757   7.86620747]
 [7.7902802  7.61945647 7.71285029]]
